name: Docker Image CI pakaci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nimeshf/test:latest
    - name: push image with tag pakaya
      run: docker login -u nimeshf -p ${{ secrets.DOCKER_TOKEN }} && docker push nimeshf/test:latest
